### ISSUE TITLE
Package clashes

### ISSUE THREAD

**Issue by cmaarkol** [IBM/ibm-generative-ai#128]
There's a ValueError when I try to import genai in my Conda environment with the following packages installed.

```#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.5                    pypi_0    pypi
aiolimiter                1.1.0                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
backoff                   2.2.1                    pypi_0    pypi
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.05.30           hca03da5_0  
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
chromadb                  0.3.27                   pypi_0    pypi
click                     8.1.6                    pypi_0    pypi
clickhouse-connect        0.6.8                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
duckdb                    0.8.1                    pypi_0    pypi
fastapi                   0.85.1                   pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hnswlib                   0.7.0                    pypi_0    pypi
httpcore                  0.17.3                   pypi_0    pypi
httptools                 0.6.0                    pypi_0    pypi
httpx                     0.24.1                   pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
ibm-generative-ai         0.2.4                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.1                    pypi_0    pypi
libffi                    3.4.4                hca03da5_0  
lz4                       4.3.2                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
monotonic                 1.6                      pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0  
networkx                  3.1                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numpy                     1.25.2                   pypi_0    pypi
onnxruntime               1.15.1                   pypi_0    pypi
openssl                   3.0.10               h1a28f6b_0  
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1          py311hca03da5_0  
posthog                   3.0.1                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
pulsar-client             3.2.0                    pypi_0    pypi
pydantic                  1.9.0                    pypi_0    pypi
python                    3.11.4               hb885b13_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             1.0.0                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
regex                     2023.6.3                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rouge-score               0.1.2                    pypi_0    pypi
safetensors               0.3.2                    pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.11.1                   pypi_0    pypi
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
setuptools                68.0.0          py311hca03da5_0  
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h80987f9_0  
starlette                 0.20.4                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.65.1                   pypi_0    pypi
transformers              4.31.0                   pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.16                  pypi_0    pypi
uvicorn                   0.23.2                   pypi_0    pypi
uvloop                    0.17.0                   pypi_0    pypi
watchfiles                0.19.0                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
wheel                     0.38.4          py311hca03da5_0  
xz                        5.4.2                h80987f9_0  
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.16.2                   pypi_0    pypi
zlib                      1.2.13               h5a0b063_0  
zstandard                 0.21.0                   pypi_0    pypi
```

### Version Information
 - Package Version: 0.2.4
 - Operating System: Mac M2

### What is the expected behavior?
Run

### What is the actual behavior?
ValueError when importing genai
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/__init__.py", line 5, in <module>
    from genai.metadata import Metadata
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/metadata.py", line 4, in <module>
    from genai.exceptions import GenAiException
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/exceptions/__init__.py", line 1, in <module>
    from genai.exceptions.genai_exception import GenAiException
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/exceptions/genai_exception.py", line 7, in <module>
    from genai.schemas.responses import ErrorResponse
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/schemas/__init__.py", line 3, in <module>
    from genai.schemas.generate_params import (
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/genai/schemas/generate_params.py", line 48, in <module>
    class GenerateParams(BaseModel):
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/pydantic/main.py", line 291, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/site-packages/pydantic/utils.py", line 256, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "/Users/carolmak/miniconda3/envs/bam/lib/python3.11/inspect.py", line 2725, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'return' is not a valid parameter name
```

### Please provide a unit test that demonstrates the bug.
```
pip install ibm-generative-ai
pip install chromadb==0.3.27
pip install sentence_transformers
pip install pandas
pip install rouge_score
pip install nltk
```

### Other notes on how to reproduce the issue?
These packages are installed in a Conda environment. However, I don't think that is the issue. 

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by jpwsutton** [comment]
Hi @cmaarkol Thanks for raising this issue.

I've had a look and I think the issue is with the version of pydantic that's being installed. chromadb 0.3.27 requires pydantic 1.9.0 and our requirements were lax enough to allow this to happen.

It looks like at version 1.9.0 pydantic has an issue with our generate params schema. I think we should be pinning our version at 1.10.0 rather than <=1.10.0. 

https://github.com/IBM/ibm-generative-ai/blob/30af41e8c541f174a8e45e5331029445fe1b02a1/pyproject.toml#L24C13-L24C22

Going forward, our fix will be to pin the version, but that will mean you'll need to change to a newer version of chromadb that works with pydantic 1.10.0.

**Comment by cmaarkol** [comment]
Thanks @jpwsutton. Installing pydantic 1.10.10 and updating chromadb to version 0.4.5 works.
