### ISSUE TITLE
server gets disconnected unexpeectedly for long prompts

### ISSUE THREAD

**Issue by eknath2k** [IBM/ibm-generative-ai#171]
### Version Information
 - Package Version:   ibm-generative-ai
 - Operating System:  linux 

### What is the expected behavior?
give a rsponse after running the prompt
### What is the actual behavior?
genai.exceptions.genai_exception.GenAiException: Server disconnected without sending a response.
### Can you identify the location in the GENAI source code where the problem exists?
Traceback (most recent call last):
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 226, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/genai/services/service_interface.py", line 73, in generate
    res = RequestHandler.post(
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/genai/services/request_handler.py", line 273, in post
    response = s.post(url=endpoint, headers=headers, json=json_data, files=files)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/blackhole/eknath/mygenai/pygenai2.py", line 174, in <module>
    main()
  File "/blackhole/eknath/mygenai/pygenai2.py", line 156, in main
    response_gen = m.service.generate(
  File "/gsa/yktgsa/home/e/k/eknath/.pyenv/versions/mygenai/lib/python3.9/site-packages/genai/services/service_interface.py", line 84, in generate
    raise GenAiException(e)
genai.exceptions.genai_exception.GenAiException: Server disconnected without sending a response.

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Tomas2D** [comment]
Hello @eknath2k, please provide package version (0.2.7 or ensure your are running the latest version).

**Comment by eknath2k** [comment]
yes it is version 0.2.7


From: Tomáš Dvořák ***@***.***>
Date: Sunday, September 24, 2023 at 5:18 AM
To: IBM/ibm-generative-ai ***@***.***>
Cc: K Ekanadham ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBM/ibm-generative-ai] server gets disconnected unexpeectedly for long prompts (Issue #171)
Hello @eknath2k, please provide the package version (0. 2. 7 or ensure you are running the latest version). — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: 
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2O-u7PHcoZPRGY9Rc0vtxPnLBCAn1qRL-JG_g-44oWbQYD-LQ9eruvfeySnS-fz9HgW3BJvrqMrPkQxG-0CGJgfmCp2QlcM2wOAR_hvHhg$>   ‌
ZjQcmQRYFpfptBannerEnd

Hello @eknath2k<https://github.com/eknath2k>, please provide the package version (0.2.7 or ensure you are running the latest version).

**Comment by Tomas2D** [comment]
The error is related to API, not to SDK. Closing for now.
