### ISSUE TITLE
genai.exceptions.genai_exception.GenAiException: <Response [400 Bad Request]>

### ISSUE THREAD

**Issue by dove-young** [IBM/ibm-generative-ai#33]
### Version Information
 - Package Version: 0.1.15
 - Operating System: RHEL 8.8

### What is the expected behavior?

The example would run and success 

### What is the actual behavior?

```
[root@st2-bastion-dev21]# python3 examples/user/explain_my_code.py

------------- Example (Explain my code)-------------

def add_numbers(number_one, number_two):
    return number_one + number_two
# Explanation of what the code does

Traceback (most recent call last):
  File "/root/jupyter/ibm-generative-ai/examples/user/explain_my_code.py", line 37, in <module>
    responses = code_explainer.generate([prompt])
  File "/usr/local/lib/python3.9/site-packages/genai/model.py", line 123, in generate
    return list(self.generate_as_completed(prompts))
  File "/usr/local/lib/python3.9/site-packages/genai/model.py", line 107, in generate_as_completed
    raise me
  File "/usr/local/lib/python3.9/site-packages/genai/model.py", line 105, in generate_as_completed
    raise GenAiException(response_gen)
genai.exceptions.genai_exception.GenAiException: <Response [400 Bad Request]>

```

### Other notes on how to reproduce the issue?

I am using alternative API with GenAI library. 

`GENAI_API=https://<alternative>-api.res.ibm.com/v1`

### Can you identify the location in the GENAI source code where the problem exists?

The output includes file name and line numbers

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by onkarbhardwaj** [comment]
@dove-young : We have tested the library with other endpoints. You might need to add appropriate GENAI_KEY along with GENAI_API in `.env` -- note that each endpoint could have a separate key. Afterwards, you need to make sure you are on a network that can reach your desired endpoint. Please also make sure in your code you are correctly reading `.env` file.

Initialize your creds as shown in the code below.

```python
import time, os
from dotenv import load_dotenv
from genai.credentials import Credentials
from genai.model import Model
from genai.schemas import GenerateParams, ModelType

load_dotenv()
api_key = os.getenv("GENAI_KEY", None)
api_url = os.getenv("GENAI_API", None)
creds = Credentials(api_key, api_endpoint=api_url)

print("\n------------- Example (Model Talk)-------------\n")

bob_params = GenerateParams(decoding_method="sample", max_new_tokens=25, temperature=1)
alice_params = GenerateParams(decoding_method="sample", max_new_tokens=45, temperature=0)
bob = Model(ModelType.FLAN_UL2, params=bob_params, credentials=creds)
alice = Model(ModelType.FLAN_T5, params=alice_params, credentials=creds)

sentence = "Hello! How are you?"

print(f"[Alice] --> {sentence}")
while True:
    bob_response = bob.generate([sentence])
    # from first batch get first result generated text
    bob_gen = bob_response[0].generated_text
    print(f"[Bob] --> {bob_gen}")

    alice_response = alice.generate([bob_gen])
    # from first batch get first result generated text
    alice_gen = alice_response[0].generated_text
    print(f"[Alice] --> {alice_gen}")

    sentence = alice_gen
    time.sleep(0.5)


```
